version: "3.8"

services:
  app:
    image: piyushinsys/petclinic:latest
    container_name: petclinic_app
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/petclinic
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
    depends_on:
      db:
        condition: service_healthy
    networks:
      - petclinic_net

  db:
    image: mysql:8.0
    container_name: petclinic_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petclinic
      MYSQL_USER: petclinic
      MYSQL_PASSWORD: petclinic
    ports:
      - "3100:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - petclinic_net

networks:
  petclinic_net:
    driver: bridge

volumes:
  db_data:
